kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitor-manager
subjects:
- kind: ServiceAccount
  name: monitor-manager
  namespace: tf-system
roleRef:
  kind: ClusterRole
  name: monitor-manager
  apiGroup: rbac.authorization.k8s.io