apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-manager
  namespace: tf-system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: monitor-manager
      component: manager
  template:
    metadata:
      labels:
        app: monitor-manager
        component: manager
    spec:
      serviceAccountName: monitor-manager
      containers:
      - name: monitor-manager
        image: "ghcr.io/galleybytes/monitor-manager:0.0.0"
        imagePullPolicy: IfNotPresent
        env:
        - name: API_USERNAME
          value: isa
        - name: API_PASSWORD
          value: 1st t1me ch4rm!
        args:
        - -tls-key=/certs/tls.key
        - -tls-cert=/certs/tls.crt
        - -ca-cert=/certs/ca.crt
        - -ca-key=/certs/ca.key
        - -secret-name=monitor-manager-certs
        - -namespace=tf-system # TODO enable env for this
        - -service-name=monitor-manager # TODO enable env for this
        - -ignore-tag=monitor.galleybytes.com/ignore
        - -monitor-image=ghcr.io/galleybytes/monitor:0.0.0-3-g8d7f3ce-dirty
        - -api=http://terraform-operator-api.tf-system.svc
        - -manager=https://monitor-manager.tf-system.svc
        - -cluster-name=kind-kind
        - -image-pull-policy=IfNotPresent
        resources:
          limits:
            cpu: 50m
            memory: 128M
          requests:
            cpu: 25m
            memory: 128M
        ports:
        - name: https
          containerPort: 8443
          protocol: TCP
        volumeMounts:
        - name: certs
          mountPath: /certs
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: monitor-manager-certs
          optional: true
          defaultMode: 0600
