name: Build and release the monitor manager

on:
  pull_request:
    branches:
    - master
  push:
    tags:
    - 'manager-*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - run: pip install docker
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Log in to registry
      # This is where you will update the PAT to GITHUB_TOKEN
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: release
      run: |
        cd manager
        RELEASE_PROJECT=true /bin/bash release.sh